catalog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
# from django.views.generic import RedirectView

from .views import (CatalogHomeView, CategoryView, SellerView, GetCategoryAttrs,
                    ProductView, AddReviewView, CompareProductsView,
                    AddProductView, AddImagesView, AddColorsView, AddRelatedProductsView, AddCompleteView,)


urlpatterns = [
    url(r'^$', CatalogHomeView.as_view(), name='home'),
    url(r'^category/(?P<slug>[^/]+)/$', CategoryView.as_view(), name='category'),
    url(r'^category/(?P<pk>\d+)/attrs/$', GetCategoryAttrs.as_view(), name='get-category-attrs'),

    url(r'^seller/(?P<seller_id>\d+)/$', SellerView.as_view(), name='seller'),
    url(r'^seller/(?P<seller_id>\d+)/(?P<category_slug>[^/]+)/$', SellerView.as_view(), name='seller-category'),

    url(r'^product/(?P<pk>\d+)/$', ProductView.as_view(), name='product'),
    url(r'^add_review/$', AddReviewView.as_view(), name='add-review'),

    url(r'^compare/$', CompareProductsView.as_view(), name='compare'),

    url(r'^add/$', AddProductView.as_view(), name='add'),
    url(r'^add/(?P<pk>\d+)/images/$', AddImagesView.as_view(), name='add-images'),
    url(r'^add/(?P<pk>\d+)/colors/$', AddColorsView.as_view(), name='add-colors'),
    url(r'^add/(?P<pk>\d+)/related/$', AddRelatedProductsView.as_view(), name='add-related'),
    url(r'^add/(?P<pk>\d+)/complete/$', AddCompleteView.as_view(), name='add-complete'),
]

lk/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import (ProfileHomeView, ProfileTemplateView, OrderView, EditProfileView, RemoveProfileView,
                    SellerTemplateView, SellerOrdersView, InvoiceRequestView, DocumentsRequestView,
                    ProductsView, ProductView,
                    ProductEditView, ProductEditImagesView, ProductEditColorsView, ProductEditRelatedView)
from .api_views import AddToFavorites, RemoveFromFavorites, AddToCompare, RemoveFromCompare
from .update_views import HumanUpdateView, FirstCompanyUpdateView, SecondCompanyUpdateView, PasswordUpdateView


urlpatterns = [
    url(r'^$', ProfileHomeView.as_view(), name='home'),
    url(r'^remove/$', RemoveProfileView.as_view(), name='remove'),

    url(r'^orders/$', ProfileTemplateView.as_view(template_name='profile/orders.html'), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', OrderView.as_view(), name='order'),

    # url(r'^reviews/$', ProfileTemplateView.as_view(template_name='profile/reviews.html'), name='reviews'),
    url(r'^reviews/$', RedirectView.as_view(pattern_name='profile:home', permanent=False), name='reviews'),

    url(r'^wishlist/$', ProfileTemplateView.as_view(template_name='profile/wishlist.html'), name='wishlist'),
    url(r'^favorites/add/$', AddToFavorites.as_view(), name='add-to-favorites'),
    url(r'^favorites/remove/$', RemoveFromFavorites.as_view(), name='remove-from-favorites'),

    url(r'^compare/add/$', AddToCompare.as_view(), name='add-to-compare'),
    url(r'^compare/remove/$', RemoveFromCompare.as_view(), name='remove-from-compare'),

    url(r'^seller_orders/$', SellerOrdersView.as_view(), name='seller-orders'),

    url(r'^products/$', ProductsView.as_view(), name='products'),
    url(r'^products/(?P<pk>\d+)/$', ProductView.as_view(), name='product'),
    url(r'^products/(?P<pk>\d+)/edit/$', ProductEditView.as_view(), name='product-edit'),
    url(r'^products/(?P<pk>\d+)/edit/images/$', ProductEditImagesView.as_view(), name='product-edit-images'),
    url(r'^products/(?P<pk>\d+)/edit/colors/$', ProductEditColorsView.as_view(), name='product-edit-colors'),
    url(r'^products/(?P<pk>\d+)/edit/related/$', ProductEditRelatedView.as_view(), name='product-edit-related'),

    url(r'^invoice/$', InvoiceRequestView.as_view(), name='invoice'),
    url(r'^documents/$', DocumentsRequestView.as_view(), name='documents'),

    url(r'^edit/$', EditProfileView.as_view(), name='edit'),
    url(r'^edit/human/$', HumanUpdateView.as_view(), name='update-human'),
    url(r'^edit/company/1/$', FirstCompanyUpdateView.as_view(), name='update-company-1'),
    url(r'^edit/company/2/$', SecondCompanyUpdateView.as_view(), name='update-company-2'),
    url(r'^edit/password/$', PasswordUpdateView.as_view(), name='update-password'),
]

main/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from lk.auth_views import SellerRegistrationView, AjaxLoginView
from catalog.views import ProductRequestView
from content.views import IndexView, PageView, AboutUsPageView, FeedbackFormView, SubscribeFormView, SearchView
from support.views import SupportView, SupportSearchView, QuestionFormView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),
    url(r'^500/$', TemplateView.as_view(template_name='500.html'), name='500'),
    url(r'^about/$', AboutUsPageView.as_view(), name='about'),

    url(r'^support/$', SupportView.as_view(), name='support'),
    url(r'^support/search/$', SupportSearchView.as_view(), name='support-search'),

    # url(r'^auth/',  include('lk.auth.urls', namespace='auth')),
    url(r'^auth/', include('registration.backends.default.urls')),
    url(r'^auth/register/seller/$', SellerRegistrationView.as_view(), name='seller_registration_register'),
    url(r'^auth/login/ajax/$', AjaxLoginView.as_view(), name='auth-ajax-login'),

    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^alazone-adm/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^treenav/', include('treenav.urls')),

    url(r'^profile/',  include('lk.urls', namespace='profile')),
    url(r'^cart/',  include('cart.urls', namespace='cart')),
    url(r'^basket/',  include('cart.api.urls', namespace='basket')),
    url(r'^shop/',  include('catalog.urls', namespace='shop')),
    url(r'^blog/',  include('blog.urls', namespace='blog')),

    # url(r'^forms/', include('feedback.urls', namespace='forms')),
    url(r'^feedback_form/$', FeedbackFormView.as_view(), name='feedback-form'),
    url(r'^subscribe_form/$', SubscribeFormView.as_view(), name='subscribe-form'),
    url(r'^question_form/$', QuestionFormView.as_view(), name='question-form'),
    url(r'^request_form/$', ProductRequestView.as_view(), name='request-form'),

    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^(?P<slug>[^/]+)/$', PageView.as_view(), name='page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lk/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin

from smart_selects.db_fields import ChainedForeignKey

import catalog
from geo.models import Country, Region


class UserManager(BaseUserManager):

    def create_user(self, email, password):

        if not email:
            raise ValueError('E-mail: обязательное поле')

        if not password:
            raise ValueError('Пароль: обязательное поле')

        user = self.model(
            email=UserManager.normalize_email(email),
        )
        user.set_password(password)
        user.save()

        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password,
        )

        user.is_staff = True
        user.is_superuser = True
        user.save()

        return user


class Profile(AbstractBaseUser, PermissionsMixin):
    PROFILE_CHOICES = (
        ('human', 'Покупатель'),
        ('company', 'Продавец'),
    )

    # Общие данные
    email = models.EmailField('E-mail', max_length=255, unique=True)
    date_joined = models.DateTimeField('Дата регистрации', auto_now_add=True)
    first_name = models.CharField('Имя', max_length=255, null=True, blank=True)
    last_name = models.CharField('Фамилия', max_length=255, null=True, blank=True)
    phone = models.CharField('Телефон', max_length=255, null=True, blank=True)
    profile_type = models.CharField('Тип профиля', choices=PROFILE_CHOICES, max_length=10, default='human')

    # Данные продавца
    company_name = models.CharField('Название компании', max_length=255, null=True, blank=True)
    image = models.ImageField('Изображение', null=True, blank=True, upload_to='sellers/')
    phone2 = models.CharField('Телефон №2', max_length=255, null=True, blank=True)
    postal_code = models.CharField('Почтовый код', max_length=255, null=True, blank=True)
    country = models.ForeignKey(Country, verbose_name='Страна', null=True, blank=True)
    region = ChainedForeignKey(
        Region, verbose_name='Регион', null=True, blank=True,
        chained_field='country', chained_model_field='country',
        show_all=False, auto_choose=True
    )
    city = models.CharField('Город', max_length=255, null=True, blank=True)
    address1 = models.CharField('Адрес №1', max_length=255, null=True, blank=True)
    address2 = models.CharField('Адрес №2', max_length=255, null=True, blank=True)

    # Управление доступами
    is_staff = models.BooleanField('Имеет доступ к административной панели сайта', default=False)
    is_active = models.BooleanField('Активен', default=True)
    active_sig = models.CharField(max_length=50, default='', blank=True)
    is_blocked = models.BooleanField('Заблокирован', default=False,
                                     help_text='Поставьте галочку, чтобы заблокировать пользователя')

    favorites = models.ManyToManyField('catalog.Product', verbose_name='Список желаний',
                                       blank=True, related_name='in_favorites')
    objects = UserManager()

    USERNAME_FIELD = 'email'

    def get_address(self):
        return '{0} {1}, {2}, город {3}, {4}'.format(self.postal_code, self.country.title, self.region.title, self.city, self.address1)

    class Meta:
        ordering = ['-id', ]
        verbose_name = 'профиль'
        verbose_name_plural = 'профили'

    def get_full_name(self):
        return self.__unicode__()

    def get_short_name(self):
        return (self.company_name if self.profile_type == 'company' and self.company_name
                else self.first_name)

    def has_full_name(self):
        return self.first_name and self.last_name

    def __unicode__(self):
        return (
            '{0} ({1})'.format(self.company_name, self.email) if self.profile_type == 'company' and self.company_name
            else '{0} {1} ({2})'.format(self.first_name, self.last_name, self.email) if self.has_full_name()
            else self.email
        )

    def show_profile_type(self):
        return ('Покупатель' if self.profile_type == 'human'
                else 'Продавец' if self.profile_type == 'company'
                else '')
    show_profile_type.allow_tags = True
    show_profile_type.short_description = 'Тип профиля'

    def show_first_name(self):
        return self.first_name or ''
    show_first_name.allow_tags = True
    show_first_name.short_description = 'Имя'

    def show_last_name(self):
        return self.last_name or ''
    show_last_name.allow_tags = True
    show_last_name.short_description = 'Фамилия'

    def show_company_name(self):
        return self.company_name or ''
    show_company_name.allow_tags = True
    show_company_name.short_description = 'Название компании'

    def get_signature(self):
        self.active_sig = Profile.objects.make_random_password(length=40)
        self.save()
        return self.active_sig

    def activate_user(self):
        self.active_sig = ''
        self.is_active = True
        self.save()

    def reset_pass(self):
        password = Profile.objects.make_random_password(length=10)
        self.active_sig = ''
        self.set_password(password)
        # send_reset_password_email(self, password)
        self.save()

    @property
    def is_seller(self):
        return self.profile_type == 'company'

    def get_carts(self):
        return self.cart_set.filter(checked_out=True)

    # @property
    # def products(self):
    #     return self.product_set.filter(show=True)

    @property
    def reviews(self):
        return catalog.ProductReview.objects.filter(product__seller_id=self.id, show=True)

    @property
    def reviews_average(self):
        reviews = self.reviews.values_list('rating', flat=True)
        return int(round(sum(reviews)/float(len(reviews)) * 20)) if len(reviews) else 0

    @property
    def shown_products(self):
        return self.product_set.filter(show=True)

    def get_favorites(self):
        return self.favorites.filter(show=True)

    def get_seller_url(self):
        return reverse('shop:seller', kwargs={'seller_id': self.id})



class InvoiceRequest(models.Model):
    profile = models.ForeignKey(Profile, verbose_name='Профиль', limit_choices_to={'profile_type': 'company'})
    datetime = models.DateTimeField('Дата и время поступления', auto_now_add=True)

    company_name = models.CharField('Название компании', max_length=255)
    phone = models.CharField('Телефон', max_length=255)
    email = models.EmailField('Email')
    address = models.TextField('Адрес')

    class Meta:
        ordering = ['-datetime', ]
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы накладных и счет-фактур'

    def __unicode__(self):
        return '{0} ({1})'.format(self.company_name, self.datetime)


class DocumentsRequest(models.Model):
    profile = models.ForeignKey(Profile, verbose_name='Профиль', limit_choices_to={'profile_type': 'company'})
    datetime = models.DateTimeField('Дата и время поступления', auto_now_add=True)

    company_name = models.CharField('Название компании', max_length=255)
    phone = models.CharField('Телефон', max_length=255)
    email = models.EmailField('Email')
    address = models.TextField('Адрес')

    class Meta:
        ordering = ['-datetime', ]
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы документов для юр.лиц'

    def __unicode__(self):
        return '{0} ({1})'.format(self.profile.company_name, self.datetime)


class NewsletterSubscription(models.Model):
    datetime = models.DateTimeField('Дата и время подписки', auto_now_add=True)
    email = models.EmailField('Email')
    profile = models.ForeignKey(Profile, verbose_name='Профиль', null=True, blank=True)

    class Meta:
        ordering = ['-datetime', ]
        verbose_name = 'подписка'
        verbose_name_plural = 'подписки на рассылку'

    def __unicode__(self):
        return self.email

    def show_profile(self):
        return self.profile or ''
    show_profile.allow_tags = True
    show_profile.short_description = 'Профиль'

templates/profile/base.html
{% extends 'base.html' %}
{% load profile_tags %}

{% block content %}
	<section id="content">
		<div id="breadcrumb-container">
			<div class="container">
				<ul class="breadcrumb">
					<li><a href="{% url 'index' %}">Главная</a></li>
					<li><a href="{% url 'profile:home' %}">Личный кабинет</a></li>
					{% block extra_breadcrumbs %}
						<li class="active">{% block breadcrumb_title %}{% endblock %}</li>
					{% endblock %}
				</ul>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12">
          <header class="content-title">
            <h1 class="title">Личный кабинет{% if request.user.is_seller %} {{ request.user.company_name }}{% endif %}</h1>
          </header>
					<div class="tab-container left clearfix" style="margin-top: 30px;">
						<ul class="nav-tabs clearfix">
							{% get_profile_slug as get_profile_slug_response %}
							{% for profile_slug, show_link in get_profile_slug_response %}
								{% if request.user.is_seller %}
									<li class="{% if profile_slug == 'seller_orders' %}active{% endif %}"><a href="{% url 'profile:seller-orders' %}"{% if not show_link and profile_slug == 'seller_orders' %} data-toggle="tab"{% endif %}>Заказанные товары</a></li>
									<li class="{% if profile_slug == 'products' %}active{% endif %}"><a href="{% url 'profile:products' %}"{% if not show_link and profile_slug == 'products' %} data-toggle="tab"{% endif %}>Управление товарами</a></li>
									<li class="{% if profile_slug == 'invoice' %}active{% endif %}"><a href="{% url 'profile:invoice' %}"{% if not show_link and profile_slug == 'invoice' %} data-toggle="tab"{% endif %}>Заказ накладных</a></li>
									<li class="{% if profile_slug == 'documents' %}active{% endif %}"><a href="{% url 'profile:documents' %}"{% if not show_link and profile_slug == 'documents' %} data-toggle="tab"{% endif %}>Заказ документов</a></li>
								{% endif %}
								{% if request.user.get_carts.count or request.user.profile_type == 'human' %}
									<li class="{% if profile_slug == 'orders' %}active{% endif %}"><a href="{% url 'profile:orders' %}"{% if not show_link and profile_slug == 'orders' %} data-toggle="tab"{% endif %}>Мои заказы</a></li>
								{% endif %}
								{% if request.user.favorites.count or request.user.profile_type == 'human' %}
									<li class="{% if profile_slug == 'wishlist' %}active{% endif %}"><a href="{% url 'profile:wishlist' %}"{% if not show_link and profile_slug == 'wishlist' %} data-toggle="tab"{% endif %}>Мои желания</a></li>
								{% endif %}
{#								<li class="{% if profile_slug == 'reviews' %}active{% endif %}"><a href="{% url 'profile:reviews' %}"{% if not show_link and profile_slug == 'reviews' %} data-toggle="tab"{% endif %}>Мои отзывы</a></li>#}
								<li class="{% if profile_slug == 'edit' %}active{% endif %}"><a href="{% url 'profile:edit' %}"{% if not show_link and profile_slug == 'edit' %} data-toggle="tab"{% endif %}>Редактировать профиль</a></li>
								<li class="{% if profile_slug == 'remove' %}active{% endif %}"><a href="{% url 'profile:remove' %}"{% if not show_link and profile_slug == 'remove' %} data-toggle="tab"{% endif %}>Удалить профиль</a></li>
							{% endfor %}
						</ul>

						<div class="tab-content clearfix">
							<div class="tab-pane active" id="active">
								{% block tab_content %}{% endblock %}
							</div><!-- End .tab-pane -->

						</div><!-- End .tab-content -->
					</div><!-- End .tab-container -->
				</div><!-- End .col-md-12 -->
			</div>
		</div>
	</section>
{% endblock %}

templates/profile/edit.html
{% extends 'profile/base.html' %}

{% block meta_title %}{{ seo_settings.profile_edit.get_meta_title }}{% endblock %}
{% block meta_desc %}{{ seo_settings.profile_edit.get_meta_desc }}{% endblock %}
{% block meta_keyw %}{{ seo_settings.profile_edit.get_meta_keyw }}{% endblock %}

{% block breadcrumb_title %}Редактировать профиль{% endblock %}

{% block tab_content %}
	<h3>Редактировать профиль</h3>
	{% if request.user.profile_type == 'human' %}
		{% include 'profile/include/edit_human.html' with profile=request.user %}
	{% else %}
		{% include 'profile/include/edit_company.html' with profile=request.user %}
	{% endif %}
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        $(function() {
          $('input[name="new_password"]').pstrength();
        });
    </script>
{% endblock %}

templates/profile/order.html
{% extends 'profile/base.html' %}
{% load thumbnail %}

{% block meta_title %}{{ seo_settings.profile_orders.get_meta_title }}{% endblock %}
{% block meta_desc %}{{ seo_settings.profile_orders.get_meta_desc }}{% endblock %}
{% block meta_keyw %}{{ seo_settings.profile_orders.get_meta_keyw }}{% endblock %}

{% block extra_breadcrumbs %}
	<li><a href="{% url 'profile:orders' %}">Мои заказы</a></li>
	<li class="active">Заказ №{{ order.id }}</li>
{% endblock %}

{% block tab_content %}
	<a href="{% url 'profile:orders' %}">< Назад</a>
	<hr/>
	<h3>Заказ №{{ order.id }} ({{ order.checkout_date|date:"d.m.Y" }})</h3>
	<table class="table cart-table">
		<thead>
			<tr>
				<th class="table-title">Наименование</th>
				<th class="table-title">Код товара</th>
				<th class="table-title">Цена</th>
				<th class="table-title">Количество</th>
				<th class="table-title">Всего</th>
			</tr>
		</thead>
		<tbody>
			{% for b_item in order.cartitem_set.all %}
				<tr>
					<td class="item-name-col">
						<figure>
							{% thumbnail b_item.product.get_cover.image '180x180' crop='center' as thumb %}
								<a href="{{ b_item.product.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ b_item.product.title }}"></a>
							{% endthumbnail %}
						</figure>
						<header class="item-name"><a href="{{ b_item.product.get_absolute_url }}">{{ b_item.product.title }}</a></header>
						{% if b_item.color_title %}
							<ul>
								<li>Цвет: {{ b_item.color_title }}</li>
							</ul>
						{% endif %}
					</td>
					<td class="item-code">{{ b_item.product_id }}</td>
					<td class="item-price-col"><span class="item-price-special">{{ b_item.price }}</span></td>
					<td>
						<span>{{ b_item.quantity }}</span>
					</td>
					<td class="item-total-col"><span class="item-price-special">{{ b_item.total_price }}</span>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/profile/product.html
{% extends 'profile/base.html' %}
{% load thumbnail %}

{% block meta_title %}{{ seo_settings.profile_products.get_meta_title }}{% endblock %}
{% block meta_desc %}{{ seo_settings.profile_products.get_meta_desc }}{% endblock %}
{% block meta_keyw %}{{ seo_settings.profile_products.get_meta_keyw }}{% endblock %}

{% block extra_breadcrumbs %}
	<li><a href="{% url 'profile:products' %}">Управление товарами</a></li>
	<li class="active">{{ product.title }}</li>
{% endblock %}

{% block tab_content %}
	<a href="{% url 'profile:products' %}">< Назад</a>
	<hr/>
	{% if product.get_cover %}
		<div class="row" style="{% if not product.get_cover %}height: 100px;{% else %}{% endif %}">
			<div class="col-md-6 col-sm-12 col-xs-12 product-viewer clearfix">
				<div id="product-image-container">
					<figure>
						{% if product.is_new %}<span class="new-rect">New</span>{% endif %}
						{% if product.get_discount %}<span class="discount-rect">-{{ product.get_discount }}%</span>{% endif %}
						{% if product.show %}<a href="{{ product.get_absolute_url }}">{% endif %}<img src="{% thumbnail product.get_cover.image '800' upscale=False as cover %}{{ cover.url }}{% endthumbnail %}" data-zoom-image="{{ product.get_cover.image.url }}" alt="{{ product.get_cover.title|default:product.title }}" id="product-image">
						<figcaption class="item-price-container">
							{% if product.new_price %}
								<span class="old-price">{{ product.show_price }}</span>
								<span class="item-price">{{ product.show_new_price }}</span>
							{% else %}
								<span class="item-price">{{ product.show_price }}</span>
							{% endif %}
						</figcaption>
						{% if product.show %}</a>{% endif %}
					</figure>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 col-xs-4"{% if product.get_cover %} style="margin-left: 50px;"{% endif %}>
				<a href="{% url 'profile:product-edit' product.id %}" class="btn btn-default btn-block">Изменить товар</a>
				<a href="{% url 'profile:product-edit-images' product.id %}" class="btn btn-default btn-block">Изменить изображения</a>
				<a href="{% url 'profile:product-edit-colors' product.id %}" class="btn btn-default btn-block">Изменить цвета</a>
				<a href="{% url 'profile:product-edit-related' product.id %}" class="btn btn-default btn-block">Изменить связанные товары</a>
			</div>
		</div>
	{% endif %}

	<div class="col-md-6 col-sm-12 col-xs-12 product" style="padding: 0">
		<div class="lg-margin visible-sm visible-xs"></div>
		{% if product.show %}<a href="{{ product.get_absolute_url }}"><h3 class="product-name" style="margin-bottom: 10px;">{{ product.title }}</h3></a>
		{% else %}<h3 class="product-name" style="margin-bottom: 10px;">{{ product.title }}</h3>
		{% endif %}
		<div class="ratings-container">
			<div class="ratings separator">
				<div class="ratings-result" data-result="{{ product.reviews_average }}"></div>
			</div>
			<span class="ratings-amount separator">
				отзывов: {{ product.reviews.count }}
			</span>
		</div>
		<ul class="product-list">
			<li><span>Статус:</span>{% if product.removed %}Удален{% elif not product.show %}Не опубликован{% elif not product.apply_changes %}Изменен, ждет одобрения{% else %}Опубликован{% endif %}</li>
			<br/>
			<li><span>Код товара:</span>{{ product.id }}</li>
			<li><span>Категория:</span>{{ product.category.title }}</li>
			<li><span>Цена:</span>{% if not product.new_price %}{{ product.price }} тнг.{% else %}<s>{{ product.price }}</s> {{ product.new_price }} тнг.{% endif %}</li>
			<li><span>Количество:</span>{{ product.quantity|default:"нет в наличии" }}</li>
			{% for attr in product.show_attrs %}
				{% if forloop.first %}<br/>{% endif %}
				{{ attr|safe }}
			{% endfor %}
		</ul>
		<br/>
		{% if product.colors.count %}
			<div class="product-color-filter-container">
				<span>Цвета:</span>
				<div class="xs-margin"></div>
				<ul class="filter-color-list clearfix">
					{% for color in product.colors.all %}
						<li><span data-bgcolor="{{ color.hex_value }}" class="filter-color-box"></span></li>
					{% endfor %}
				</ul>
			</div>
		{% endif %}
		<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#remove-product">Удалить товар</button>
		<hr/>
	</div>
	{% if not product.get_cover %}
		<div class="col-md-4 col-sm-4 col-xs-4">
			<a href="{% url 'profile:product-edit' product.id %}" class="btn btn-default btn-block">Изменить товар</a>
			<a href="{% url 'profile:product-edit-images' product.id %}" class="btn btn-default btn-block">Изменить изображения</a>
			<a href="{% url 'profile:product-edit-colors' product.id %}" class="btn btn-default btn-block">Изменить цвета</a>
		</div>
	{% endif %}
{% endblock %}

{% block popups %}
	<div class="modal fade" id="remove-product" tabindex="-1" role="dialog" aria-labelledby="remove-product" aria-hidden="true" style="display: none;">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h4 class="modal-title" id="myModalLabel3">Удаление товара</h4>
				</div><!-- End .modal-header -->
				<div class="modal-body">
					<p>Удаление товара - необратимая вещь. Вы уверены, что хотите это сделать?</p>
				</div><!-- End .modal-body -->
				<form action="{{ request.path }}" method="post" class="remove_profile_form">
					{% csrf_token %}
					<div class="modal-footer">
						<button type="button" class="btn btn-link" data-dismiss="modal">Закрыть</button>
						<button type="submit" class="btn btn-danger">Удалить</button>
					</div><!-- End .modal-footer -->
				</form>
			</div><!-- End .modal-content -->
		</div><!-- End .modal-dialog -->
	</div>
{% endblock %}