cart/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import CartAjaxView


urlpatterns = [
    url(r'^add/$', CartAjaxView.as_view(action='add'), name='add'),
    url(r'^change/$', CartAjaxView.as_view(action='set'), name='change'),
    url(r'^delete/$', CartAjaxView.as_view(action='remove'), name='delete'),
    url(r'^clear/$', CartAjaxView.as_view(action='clear'), name='clear'),
]

cart/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

# from .views import CartView, CheckoutView
from .views import CheckoutView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="cart/cart.html"), name='home'),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout'),
    url(r'^checkout/registration/$', CheckoutView.as_view(form_type='with_registration'), name='checkout-registration'),
]

lk/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import (ProfileHomeView, ProfileTemplateView, OrderView, EditProfileView, RemoveProfileView,
                    SellerTemplateView, SellerOrdersView, InvoiceRequestView, DocumentsRequestView,
                    ProductsView, ProductView,
                    ProductEditView, ProductEditImagesView, ProductEditColorsView, ProductEditRelatedView)
from .api_views import AddToFavorites, RemoveFromFavorites, AddToCompare, RemoveFromCompare
from .update_views import HumanUpdateView, FirstCompanyUpdateView, SecondCompanyUpdateView, PasswordUpdateView


urlpatterns = [
    url(r'^$', ProfileHomeView.as_view(), name='home'),
    url(r'^remove/$', RemoveProfileView.as_view(), name='remove'),

    url(r'^orders/$', ProfileTemplateView.as_view(template_name='profile/orders.html'), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', OrderView.as_view(), name='order'),

    # url(r'^reviews/$', ProfileTemplateView.as_view(template_name='profile/reviews.html'), name='reviews'),
    url(r'^reviews/$', RedirectView.as_view(pattern_name='profile:home', permanent=False), name='reviews'),

    url(r'^wishlist/$', ProfileTemplateView.as_view(template_name='profile/wishlist.html'), name='wishlist'),
    url(r'^favorites/add/$', AddToFavorites.as_view(), name='add-to-favorites'),
    url(r'^favorites/remove/$', RemoveFromFavorites.as_view(), name='remove-from-favorites'),

    url(r'^compare/add/$', AddToCompare.as_view(), name='add-to-compare'),
    url(r'^compare/remove/$', RemoveFromCompare.as_view(), name='remove-from-compare'),

    url(r'^seller_orders/$', SellerOrdersView.as_view(), name='seller-orders'),

    url(r'^products/$', ProductsView.as_view(), name='products'),
    url(r'^products/(?P<pk>\d+)/$', ProductView.as_view(), name='product'),
    url(r'^products/(?P<pk>\d+)/edit/$', ProductEditView.as_view(), name='product-edit'),
    url(r'^products/(?P<pk>\d+)/edit/images/$', ProductEditImagesView.as_view(), name='product-edit-images'),
    url(r'^products/(?P<pk>\d+)/edit/colors/$', ProductEditColorsView.as_view(), name='product-edit-colors'),
    url(r'^products/(?P<pk>\d+)/edit/related/$', ProductEditRelatedView.as_view(), name='product-edit-related'),

    url(r'^invoice/$', InvoiceRequestView.as_view(), name='invoice'),
    url(r'^documents/$', DocumentsRequestView.as_view(), name='documents'),

    url(r'^edit/$', EditProfileView.as_view(), name='edit'),
    url(r'^edit/human/$', HumanUpdateView.as_view(), name='update-human'),
    url(r'^edit/company/1/$', FirstCompanyUpdateView.as_view(), name='update-company-1'),
    url(r'^edit/company/2/$', SecondCompanyUpdateView.as_view(), name='update-company-2'),
    url(r'^edit/password/$', PasswordUpdateView.as_view(), name='update-password'),
]

main/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from lk.auth_views import SellerRegistrationView, AjaxLoginView
from catalog.views import ProductRequestView
from content.views import IndexView, PageView, AboutUsPageView, FeedbackFormView, SubscribeFormView, SearchView
from support.views import SupportView, SupportSearchView, QuestionFormView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),
    url(r'^500/$', TemplateView.as_view(template_name='500.html'), name='500'),
    url(r'^about/$', AboutUsPageView.as_view(), name='about'),

    url(r'^support/$', SupportView.as_view(), name='support'),
    url(r'^support/search/$', SupportSearchView.as_view(), name='support-search'),

    # url(r'^auth/',  include('lk.auth.urls', namespace='auth')),
    url(r'^auth/', include('registration.backends.default.urls')),
    url(r'^auth/register/seller/$', SellerRegistrationView.as_view(), name='seller_registration_register'),
    url(r'^auth/login/ajax/$', AjaxLoginView.as_view(), name='auth-ajax-login'),

    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^alazone-adm/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^treenav/', include('treenav.urls')),

    url(r'^profile/',  include('lk.urls', namespace='profile')),
    url(r'^cart/',  include('cart.urls', namespace='cart')),
    url(r'^basket/',  include('cart.api.urls', namespace='basket')),
    url(r'^shop/',  include('catalog.urls', namespace='shop')),
    url(r'^blog/',  include('blog.urls', namespace='blog')),

    # url(r'^forms/', include('feedback.urls', namespace='forms')),
    url(r'^feedback_form/$', FeedbackFormView.as_view(), name='feedback-form'),
    url(r'^subscribe_form/$', SubscribeFormView.as_view(), name='subscribe-form'),
    url(r'^question_form/$', QuestionFormView.as_view(), name='question-form'),
    url(r'^request_form/$', ProductRequestView.as_view(), name='request-form'),

    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^(?P<slug>[^/]+)/$', PageView.as_view(), name='page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from core.utils import validate_password
from lk.models import Profile
from .models import Cart as CartModel


# class CheckoutFormWithoutRegistration(forms.Form):
#     delivery_type = forms.CharField(widget=forms.PasswordInput)
#     payment_type = forms.CharField(widget=forms.PasswordInput)


class CheckoutFormWithoutRegistration(forms.ModelForm):

    class Meta:
        model = CartModel
        fields = ('email', 'first_name', 'last_name', 'phone', 'phone2',
                  'address1', 'address2', 'city', 'region', 'postal_code', 'country',
                  'delivery_type', 'payment_type',)

    def __init__(self, *args, **kwargs):
        super(CheckoutFormWithoutRegistration, self).__init__(*args, **kwargs)

        for _, field in self.fields.iteritems():
            if field.label not in ('Телефон №2', 'Адрес №2'):
                field.required = True

        self.fields['delivery_type'].widget.attrs.update({'class': 'form-control input-lg'})
        self.fields['payment_type'].widget.attrs.update({'class': 'form-control input-lg'})


class CheckoutFormWithRegistration(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(widget=forms.PasswordInput, required=True)

    class Meta:
        model = CartModel
        fields = ('email', 'first_name', 'last_name', 'phone', 'phone2',
                  'address1', 'address2', 'city', 'region', 'postal_code', 'country',
                  'delivery_type', 'payment_type',)

    def __init__(self, *args, **kwargs):
        super(CheckoutFormWithRegistration, self).__init__(*args, **kwargs)

        for _, field in self.fields.iteritems():
            if field.label not in ('Телефон №2', 'Адрес №2'):
                field.required = True

        self.fields['delivery_type'].widget.attrs.update({'class': 'form-control input-lg'})
        self.fields['payment_type'].widget.attrs.update({'class': 'form-control input-lg'})

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        res = validate_password(password1)
        if res != 'ok':
            raise forms.ValidationError(res)
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        print password1, password2
        if not password1 == password2:
            raise forms.ValidationError('Пароли не совпадают')
        return password2

    # def clean_password2(self):
    #     password1 = self.cleaned_data.get('password1')
    #     password2 = self.cleaned_data.get('password2')
    #     if not password1 == password2:
    #         raise forms.ValidationError('')
    #     return password2

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Profile.objects.filter(email=email).count():
            raise forms.ValidationError('Такой email уже занят.')
        return email

cart/api/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import Http404, JsonResponse
from django.views.generic import View

from catalog.models import Product, ProductColor
from cart.cart import Cart


class CartAjaxView(View):
    """
    Обрабатываем аякс-запросы на изменение корзины: 'set', 'add', 'delete' или 'clear'
    """
    action = ''

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            errors = []
            cart = Cart(request)

            try:
                if self.action == 'clear':
                    cart.clear()

                else:
                    product = Product.objects.filter(id=int(request.POST.get('product_id'))).first()
                    quantity = int(request.POST.get('quantity', 1))
                    color_id = int(request.POST.get('color', 0))
                    color = ProductColor.objects.filter(id=color_id).first() if color_id else product.colors.first()

                    # if product and color:
                    if product:
                        if self.action == 'set':
                            if not cart.set(product, color, quantity):
                                errors = ['Недостаточно товара на складе']

                        elif self.action == 'add':
                            if not cart.add(product, color, quantity):
                                errors = ['Недостаточно товара на складе']

                        elif self.action == 'remove':
                            cart.remove(product, color)

                    else:
                        raise Http404

            except ValueError:
                # print 'value_error'
                raise Http404

            if len(errors):
                data = {'basket': [], 'errors': errors}
            else:
                data = {'basket': cart.get_basket(), 'errors': []}
            return JsonResponse(data)

        else:
            # print 'not_ajax'
            raise Http404

cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.contrib.sites.models import RequestSite
from django.contrib.sites.models import Site

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import UpdateView

from registration.models import RegistrationProfile

from lk.email import send_admin_order_email, send_customer_order_email
from lk.models import Profile
from .cart import Cart
from .forms import CheckoutFormWithoutRegistration, CheckoutFormWithRegistration


class CheckoutView(UpdateView):
    form_type = ''
    template_name = 'cart/checkout.html'
    form_classes = {
        'with_registration': CheckoutFormWithRegistration,
        'default': CheckoutFormWithoutRegistration
    }

    def get(self, request, *args, **kwargs):
        self.form_type = self.form_type or request.GET.get('t')
        if (not self.form_type in ('with_registration', 'without_registration') and self.request.user.is_anonymous()
           or not self.get_object().count()):
            return HttpResponseRedirect(reverse('cart:home'))
        return super(CheckoutView, self).get(request, *args, **kwargs)

    def get_form_class(self):
        return (self.form_classes['with_registration'] if self.form_type == 'with_registration'
                else self.form_classes['default'])
        # return CheckoutFormWithoutRegistration

    def get_success_url(self):
        return self.request.path

    def get_object(self, queryset=None):
        return Cart(self.request).cart

    def form_invalid(self, form):
        errors = []
        for k in form.errors:
            errors.append({'name': k, 'error': form.errors[k][0]})
        data = {
            'errors': errors,
            'result': 'error',
        }
        return JsonResponse(data)

    def form_valid(self, form):
        cart = form.instance

        if cart.count():
            if self.form_type == 'with_registration':
                profile = Profile.objects.create(
                    email=form.cleaned_data.get('email'),
                    is_active=False,
                    profile_type='human',
                )
                attrs = ('first_name', 'last_name', 'phone', 'phone2', 'address1', 'address2', 'city', 'postal_code')
                         # 'region', 'country',)
                for attr in attrs:
                    setattr(profile, attr, self.request.POST.get(attr))
                profile.set_password(form.cleaned_data.get('password1'))
                profile.save()
                self._create_user(self.request, profile)
                success_message = '<p>Данные о заказе отправлены на ваш email, ' \
                                  'мы будем сообщать вам об изменениях статуса заказа.</p>' \
                                  '<p>Также вам отправлена ссылка для активации профиля.</p>'
                cart.customer = profile

            elif self.request.user.is_anonymous():
                success_message = '<p>Данные о заказе отправлены на ваш email, ' \
                                  'мы будем сообщать вам об изменениях статуса заказа.</p>'
                cart.customer = None

            else:
                success_message = '<p>Данные о заказе отправлены на ваш email, ' \
                                  'мы будем сообщать вам об изменениях статуса заказа.</p>' \
                                  '<p>Вы можете просматривать историю заказов в ' \
                                  '<a href="{0}">личном кабинете</a>.</p>'.format(reverse('profile:orders'))
                # import ipdb; ipdb.set_trace()
                cart.customer = self.request.user

            cart.checked_out = True
            cart.checkout_date = datetime.datetime.now()
            cart.summary = cart.get_summary()
            cart.save()
            super(CheckoutView, self).form_valid(form)

            send_customer_order_email(email=form.cleaned_data.get('email'), request=self.request, order=cart)
            send_admin_order_email(request=self.request, order=cart)

            if self.request.session.get('CART_ID'):
                del self.request.session['CART_ID']

            return JsonResponse({'result': 'ok', 'success_message': success_message})

        else:
            return JsonResponse({'error_message': 'Корзина пуста', 'result': 'error'})

    def _create_user(self, request, new_user_instance):
        """
        registration.backends.default.views.RegistrationView
        """
        if Site._meta.installed:
            site = Site.objects.get_current()
        else:
            site = RequestSite(request)

        new_user = RegistrationProfile.objects.create_inactive_user(
            new_user=new_user_instance,
            site=site,
            send_email=True,
            request=request,
        )
        return new_user

templates/cart/cart.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block meta_title %}{{ seo_settings.cart.get_meta_title }}{% endblock %}
{% block meta_desc %}{{ seo_settings.cart.get_meta_desc }}{% endblock %}
{% block meta_keyw %}{{ seo_settings.cart.get_meta_keyw }}{% endblock %}

{% block content %}
<section id="content">
	<div id="breadcrumb-container">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="{% url 'index' %}">Главная</a></li>
				<li class="active">Корзина</li>
			</ul>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<header class="content-title">
					<h1 class="title">Корзина</h1>
					<p class="title-desc">Товары, которые Вы собираетесь купить.</p>
				</header>
				<div class="xs-margin"></div>
				<div class="row">
					<div class="col-md-12 table-responsive">
						<table class="table cart-table">
							<thead>
								<tr>
									<th class="table-title">Наименование</th>
									<th class="table-title">Код</th>
									<th class="table-title">Цена</th>
									<th class="table-title">Количество</th>
									<th class="table-title">Всего</th>
								</tr>
							</thead>
							<tbody>
								{% for b_item in basket.cartitem_set.all %}
									<tr>
										<td class="item-name-col">
											<figure>
												{% thumbnail b_item.product.get_cover.image '180x180' crop='center' as thumb %}
													<a href="{{ b_item.product.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ b_item.product.title }}"></a>
												{% endthumbnail %}
											</figure>
											<header class="item-name"><a href="{{ b_item.product.get_absolute_url }}">{{ b_item.product.title }}</a></header>
											{% if b_item.color_title %}
												<ul>
													<li>Цвет: {{ b_item.color_title }}</li>
												</ul>
											{% endif %}
										</td>
										<td class="item-code">{{ b_item.product_id }}</td>
										<td class="item-price-col"><span class="item-price-special">{{ b_item.price }}</span></td>
										<td>
											<div class="custom-quantity-input">
												<input type="text" name="quantity" value="{{ b_item.quantity }}" data-id="{{ b_item.product_id }}" data-color-id="{{ b_item.color_id }}">
												<a href="#" onclick="return false;" class="quantity-btn quantity-input-up cart"><i class="fa fa-angle-up"></i></a>
												<a href="#" onclick="return false;" class="quantity-btn quantity-input-down cart"><i class="fa fa-angle-down"></i></a>
											</div>
										</td>
										<td class="item-total-col"><span class="item-price-special">{{ b_item.total_price }}</span>
										<a href="javascript:void(0);" data-referrer="basket-cart-page" data-id="{{ b_item.product_id }}" data-color-id="{{ b_item.color_id }}" class="close-button delete-from-basket"></a>
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
				<div class="lg-margin"></div>
				<div class="row">
					<div class="col-md-4 col-sm-12 col-xs-12">

						<table class="table total-table">
							<tbody>
								<tr>
									<td class="total-table-title">Всего:</td>
									<td class="total-table-label">{{ basket_data.total_price }}</td>
								</tr>
								<tr>
									<td class="total-table-title">Доставка:</td>
									<td>0.00</td>
								</tr>
								<tr>
									<td class="total-table-title">Налог (0%):</td>
									<td>0.00</td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<td>Итого:</td>
									<td class="total-table-label">{{ basket_data.total_price }}</td>
								</tr>
							</tfoot>
						</table>
						<div class="md-margin"></div>
						<a href="{% url 'shop:home' %}" class="btn btn-custom-2">ПРОДОЛЖИТЬ ПОКУПКИ</a>
						{% if request.user.is_authenticated %}
							<a href="{% url 'cart:checkout' %}"{% if basket.cartitem_set.count == 0 %} disabled{% endif %} class="btn btn-custom checkout-header-button">ОФОРМИТЬ</a>
						{% else %}
							<button{% if basket.cartitem_set.count == 0 %} disabled{% endif %} data-toggle="modal" data-target="#checkout-login-popup" class="btn btn-custom checkout-header-button">ОФОРМИТЬ</button>
						{% endif %}

					</div>
				</div>
				<div class="md-margin2x"></div>
			</div>
		</div>
	</div>
</section>

{% endblock %}