lk/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import (ProfileHomeView, ProfileTemplateView, OrderView, EditProfileView, RemoveProfileView,
                    SellerTemplateView, SellerOrdersView, InvoiceRequestView, DocumentsRequestView,
                    ProductsView, ProductView,
                    ProductEditView, ProductEditImagesView, ProductEditColorsView, ProductEditRelatedView)
from .api_views import AddToFavorites, RemoveFromFavorites, AddToCompare, RemoveFromCompare
from .update_views import HumanUpdateView, FirstCompanyUpdateView, SecondCompanyUpdateView, PasswordUpdateView


urlpatterns = [
    url(r'^$', ProfileHomeView.as_view(), name='home'),
    url(r'^remove/$', RemoveProfileView.as_view(), name='remove'),

    url(r'^orders/$', ProfileTemplateView.as_view(template_name='profile/orders.html'), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', OrderView.as_view(), name='order'),

    # url(r'^reviews/$', ProfileTemplateView.as_view(template_name='profile/reviews.html'), name='reviews'),
    url(r'^reviews/$', RedirectView.as_view(pattern_name='profile:home', permanent=False), name='reviews'),

    url(r'^wishlist/$', ProfileTemplateView.as_view(template_name='profile/wishlist.html'), name='wishlist'),
    url(r'^favorites/add/$', AddToFavorites.as_view(), name='add-to-favorites'),
    url(r'^favorites/remove/$', RemoveFromFavorites.as_view(), name='remove-from-favorites'),

    url(r'^compare/add/$', AddToCompare.as_view(), name='add-to-compare'),
    url(r'^compare/remove/$', RemoveFromCompare.as_view(), name='remove-from-compare'),

    url(r'^seller_orders/$', SellerOrdersView.as_view(), name='seller-orders'),

    url(r'^products/$', ProductsView.as_view(), name='products'),
    url(r'^products/(?P<pk>\d+)/$', ProductView.as_view(), name='product'),
    url(r'^products/(?P<pk>\d+)/edit/$', ProductEditView.as_view(), name='product-edit'),
    url(r'^products/(?P<pk>\d+)/edit/images/$', ProductEditImagesView.as_view(), name='product-edit-images'),
    url(r'^products/(?P<pk>\d+)/edit/colors/$', ProductEditColorsView.as_view(), name='product-edit-colors'),
    url(r'^products/(?P<pk>\d+)/edit/related/$', ProductEditRelatedView.as_view(), name='product-edit-related'),

    url(r'^invoice/$', InvoiceRequestView.as_view(), name='invoice'),
    url(r'^documents/$', DocumentsRequestView.as_view(), name='documents'),

    url(r'^edit/$', EditProfileView.as_view(), name='edit'),
    url(r'^edit/human/$', HumanUpdateView.as_view(), name='update-human'),
    url(r'^edit/company/1/$', FirstCompanyUpdateView.as_view(), name='update-company-1'),
    url(r'^edit/company/2/$', SecondCompanyUpdateView.as_view(), name='update-company-2'),
    url(r'^edit/password/$', PasswordUpdateView.as_view(), name='update-password'),
]

main/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from lk.auth_views import SellerRegistrationView, AjaxLoginView
from catalog.views import ProductRequestView
from content.views import IndexView, PageView, AboutUsPageView, FeedbackFormView, SubscribeFormView, SearchView
from support.views import SupportView, SupportSearchView, QuestionFormView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),
    url(r'^500/$', TemplateView.as_view(template_name='500.html'), name='500'),
    url(r'^about/$', AboutUsPageView.as_view(), name='about'),

    url(r'^support/$', SupportView.as_view(), name='support'),
    url(r'^support/search/$', SupportSearchView.as_view(), name='support-search'),

    # url(r'^auth/',  include('lk.auth.urls', namespace='auth')),
    url(r'^auth/', include('registration.backends.default.urls')),
    url(r'^auth/register/seller/$', SellerRegistrationView.as_view(), name='seller_registration_register'),
    url(r'^auth/login/ajax/$', AjaxLoginView.as_view(), name='auth-ajax-login'),

    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^alazone-adm/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^treenav/', include('treenav.urls')),

    url(r'^profile/',  include('lk.urls', namespace='profile')),
    url(r'^cart/',  include('cart.urls', namespace='cart')),
    url(r'^basket/',  include('cart.api.urls', namespace='basket')),
    url(r'^shop/',  include('catalog.urls', namespace='shop')),
    url(r'^blog/',  include('blog.urls', namespace='blog')),

    # url(r'^forms/', include('feedback.urls', namespace='forms')),
    url(r'^feedback_form/$', FeedbackFormView.as_view(), name='feedback-form'),
    url(r'^subscribe_form/$', SubscribeFormView.as_view(), name='subscribe-form'),
    url(r'^question_form/$', QuestionFormView.as_view(), name='question-form'),
    url(r'^request_form/$', ProductRequestView.as_view(), name='request-form'),

    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^(?P<slug>[^/]+)/$', PageView.as_view(), name='page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/profile/include/category_fields.html
{% load catalog_tags %}

{% if not category %}
  {% get_category category_id as category %}
{% endif %}

{#{% for field in category.get_attrs %}#}
{#{% for field in category.attrs %}#}
{% for field in category.get_new_attrs %}
{#	{% if not field.name|endswith:'-new' %}#}

		{% if form %}
			{% for error in form|get_field_errors:field.name %}
				<div class="help-block input-error">{{ error }}</div>
			{% endfor %}
		{% endif %}

		<div class="input-group">
			<span class="input-group-addon"><span class="input-text">{{ field.kwargs.verbose_name|remove_shit }}{% if not field.kwargs.blank %}&#42;{% endif %}</span></span>

			{% if field.class == 'BooleanField' %}
				{% get_boolean_value product field.name as boolean_value %}
				<input class="form-control input-lg" id="id_{{ field.name }}" name="{{ field.name }}" type="checkbox"{% if boolean_value %} checked{% endif %}>
			{% else %}
				<input type="{% get_input_type field.class %}" name="{{ field.name }}" value="{{ product|get_value:field.name }}" class="form-control input-lg"{% if not category|get_blank_from_new:field.name %} required{% endif %} placeholder="{{ field.kwargs.verbose_name|remove_shit }}">
			{% endif %}

		</div>
{#	{% endif %}#}
{% endfor %}

templates/profile/include/edit_company.html
	<div class="row" style="margin-top: 40px;">
		<div class="col-md-6 col-sm-6 col-xs-12">
			<form class="ajax_form show_field_errors do_not_reset" action="{% url 'profile:update-company-1' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<fieldset>
					<h4>Персональные данные</h4>
					<div class="alert alert-success" style="display: none;">Данные успешно изменены.</div>
					<div class="alert alert-danger" style="display: none;"></div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-company"></span><span class="input-text">Компания&#42;</span></span>
						<input type="text" name="company_name" value="{{ profile.company_name }}" required class="form-control input-lg" placeholder="Название компании">
					</div>
					{% if profile.image %}<span>На данный момент: <a href="{{ profile.image.url }}">{{ profile.image }}</a></span>{% endif %}
					<div class="input-group">
						<span class="input-group-addon"><span class="input-text">Изображение<!--{% if not profile.image %}&#42;{% endif %}--></span></span>
						<input type="file" name="image" class="form-control input-lg" accept=".png,.jpg,.jpeg,.gif">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">Имя&#42;</span></span>
						<input type="text" name="first_name" value="{{ profile.first_name }}" required class="form-control input-lg" placeholder="Имя руководителя">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">Фамилия&#42;</span></span>
						<input type="text" name="last_name" required value="{{ profile.last_name }}" class="form-control input-lg" placeholder="Фамилия руководителя">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-email"></span><span class="input-text">Email&#42;</span></span>
						<input type="text" name="email" required value="{{ profile.email }}" class="form-control input-lg" placeholder="Email">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-phone"></span><span class="input-text">Телефон&#42;</span></span>
						<input type="text" name="phone" value="{{ profile.phone }}" required class="form-control input-lg" placeholder="Телефон">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-phone"></span><span class="input-text">Телефон №2</span></span>
						<input type="text" name="phone2" value="{{ profile.phone2|default:'' }}" class="form-control input-lg" placeholder="Дополнительный телефон (не обязательно)">
					</div>
					<input type="submit" value="СОХРАНИТЬ" class="btn btn-custom-2 md-margin">
				</fieldset>
			</form>
		</div>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<form class="ajax_form show_field_errors do_not_reset" action="{% url 'profile:update-company-2' %}" method="post">
				{% csrf_token %}
				<fieldset>
					<h4>Адресные данные продавца</h4>
					<div class="alert alert-success" style="display: none;">Данные успешно изменены.</div>
					<div class="alert alert-danger" style="display: none;"></div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-postcode"></span><span class="input-text">Почтовый код</span></span>
						<input type="text" name="postal_code" value="{{ profile.postal_code }}" class="form-control input-lg" placeholder="Почтовый код">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-country"></span><span class="input-text">Страна&#42;</span></span>
						{{ form.country }}
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-region"></span><span class="input-text">Регион&#42;</span></span>
						{{ form.region }}
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-city"></span><span class="input-text">Город&#42;</span></span>
						<input type="text" name="city" value="{{ profile.city }}" required class="form-control input-lg" placeholder="Город">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-address"></span><span class="input-text">Адрес&#42;</span></span>
						<input type="text" name="address1" value="{{ profile.address1 }}" required class="form-control input-lg" placeholder="Адрес (строка 1)">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-address"></span><span class="input-text">Адрес №2</span></span>
						<input type="text" name="address2" value="{{ profile.address2 }}" class="form-control input-lg" placeholder="Адрес (строка 2)">
					</div>
					<input type="submit" value="СОХРАНИТЬ" class="btn btn-custom-2 md-margin">
				</fieldset>
			</form>
		</div>
	</div>

	<div class="col-md-6 col-sm-6 col-xs-12" style="margin-top: -60px;">
		<form class="ajax_form show_field_errors" action="{% url 'profile:update-password' %}" method="post">
			{% csrf_token %}
			<fieldset>
				<h4>Изменить пароль</h4>
				<p>Пароль должен быть минимум из 6 символов.</p>
				<div class="alert alert-success" style="display: none;">Пароль успешно изменен.</div>
				<div class="alert alert-danger" style="display: none;"></div>
				<div class="input-group">
					<span class="input-group-addon"><span class="input-icon input-icon-password"></span><span class="input-text">Пароль&#42;</span></span>
					<input type="password" name="new_password" required class="form-control input-lg" placeholder="Новый пароль">
				</div>
				<div class="input-group">
					<span class="input-group-addon"><span class="input-icon input-icon-password"></span><span class="input-text">Пароль&#42;</span></span>
					<input type="password" name="new_password_repeat" required class="form-control input-lg" placeholder="Повторите пароль">
				</div>
				<input type="submit" value="СОХРАНИТЬ" class="btn btn-custom-2 md-margin">
			</fieldset>
		</form>
	</div>

templates/profile/include/edit_human.html
	<div class="row" style="margin-top: 40px;">
		<div class="col-md-6 col-sm-6 col-xs-12">
			<form class="ajax_form show_field_errors do_not_reset" action="{% url 'profile:update-human' %}" method="post">
				{% csrf_token %}
				<fieldset>
					<h4>Персональные данные</h4>
					<div class="alert alert-success" style="display: none;">Данные успешно изменены.</div>
					<div class="alert alert-danger" style="display: none;"></div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">Имя&#42;</span></span>
						<input type="text" name="first_name" value="{{ profile.first_name }}" required class="form-control input-lg" placeholder="Ваше имя">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">Фамилия&#42;</span></span>
						<input type="text" name="last_name" value="{{ profile.last_name }}" required class="form-control input-lg" placeholder="Ваша фамилия">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-email"></span><span class="input-text">Email&#42;</span></span>
						<input type="text" name="email" value="{{ profile.email }}" required class="form-control input-lg" placeholder="Ваш email">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-phone"></span><span class="input-text">Телефон</span></span>
						<input type="text" name="phone" value="{{ profile.phone }}" class="form-control input-lg" placeholder="Ваш телефон (не обязательно)">
					</div>
					<input type="submit" value="СОХРАНИТЬ" class="btn btn-custom-2 md-margin">
				</fieldset>
			</form>
		</div>

		<div class="col-md-6 col-sm-6 col-xs-12">
			<form class="ajax_form" action="{% url 'profile:update-password' %}" method="post">
				{% csrf_token %}
				<fieldset>
					<h4>Изменить пароль</h4>
					<p>Пароль должен быть минимум из 6 символов и содержать как минимум одну заглавную букву и одну цифру.</p>
					<div class="alert alert-success" style="display: none;">Пароль успешно изменен.</div>
					<div class="alert alert-danger" style="display: none;"></div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-password"></span><span class="input-text">Пароль&#42;</span></span>
						<input type="password" name="new_password" required class="form-control input-lg" placeholder="Новый пароль">
					</div>
					<div class="input-group">
						<span class="input-group-addon"><span class="input-icon input-icon-password"></span><span class="input-text">Пароль&#42;</span></span>
						<input type="password" name="new_password_repeat" required class="form-control input-lg" placeholder="Повторите пароль">
					</div>
					<input type="submit" value="СОХРАНИТЬ" class="btn btn-custom-2 md-margin">
				</fieldset>
			</form>
		</div>
	</div>

templates/profile/include/product.html
{% load thumbnail %}

<div class="item item-hover">
	<div class="item-image-wrapper">
		<figure class="item-image-container">
			<a href="{{ product.get_absolute_url }}">
				{% with product.get_cover as cover %}
					{% with product.get_backing as backing %}
						{% thumbnail cover.image '228x319' crop='center' as cover_thumb %}
							{% thumbnail backing.image '228x319' crop='center' as backing_thumb %}
								<img src="{{ cover_thumb.url }}" alt="{{ cover.title|default:product.title }}" class="item-image">
								<img src="{{ backing_thumb.url }}" alt="{{ backing.title|default:product.title }}" class="item-image-hover">
							{% endthumbnail %}
						{% endthumbnail %}
					{% endwith %}
				{% endwith %}
			</a>
		</figure>
{% comment %}
		<div class="item-price-container">
			{% if product.new_price %}
				<span class="old-price">{{ product.show_price }}</span>
				<span class="item-price">{{ product.show_new_price }}</span>
			{% else %}
				<span class="item-price">{{ product.show_price }}</span>
			{% endif %}
		</div>
{% endcomment %}
{#		{% if product.is_new %}<span class="new-rect">New</span>{% endif %}#}
{#		{% if product.get_discount %}<span class="discount-rect">-{{ product.get_discount }}%</span>{% endif %}#}
	</div>
{% comment %}
	<div class="item-meta-container">
		<div class="ratings-container">
			<div class="ratings">
				<div class="ratings-result" data-result="{{ product.reviews_average }}"></div>
			</div>
			<span class="ratings-amount">
				отзывов: {{ product.reviews.count }}
			</span>
		</div>
{% endcomment %}
		<h3 class="item-name"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h3>
{% comment %}
		<div class="item-action">
			<a href="javascript:void(0);" data-referrer="category-page" data-color-id="0" data-quantity="1" data-id="{{ product.id }}" class="item-add-btn add-to-basket">
				<span class="icon-cart-text">В корзину</span>
			</a>
			<div class="item-action-inner">
				<a href="#" data-add-url="{% url 'profile:add-to-favorites' %}" data-id="{{ product.id }}" class="icon-button icon-like add_to{% if not request.user.is_active or product in request.user.favorites.all %} _disabled{% endif %}">В список желаний</a>
				<a href="#" data-add-url="{% url 'profile:add-to-compare' %}" data-id="{{ product.id }}" class="icon-button icon-compare add_to _disabled">В сравнение</a>
			</div>
		</div>
	</div>
{% endcomment %}
</div>