catalog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
# from django.views.generic import RedirectView

from .views import (CatalogHomeView, CategoryView, SellerView, GetCategoryAttrs,
                    ProductView, AddReviewView, CompareProductsView,
                    AddProductView, AddImagesView, AddColorsView, AddRelatedProductsView, AddCompleteView,)


urlpatterns = [
    url(r'^$', CatalogHomeView.as_view(), name='home'),
    url(r'^category/(?P<slug>[^/]+)/$', CategoryView.as_view(), name='category'),
    url(r'^category/(?P<pk>\d+)/attrs/$', GetCategoryAttrs.as_view(), name='get-category-attrs'),

    url(r'^seller/(?P<seller_id>\d+)/$', SellerView.as_view(), name='seller'),
    url(r'^seller/(?P<seller_id>\d+)/(?P<category_slug>[^/]+)/$', SellerView.as_view(), name='seller-category'),

    url(r'^product/(?P<pk>\d+)/$', ProductView.as_view(), name='product'),
    url(r'^add_review/$', AddReviewView.as_view(), name='add-review'),

    url(r'^compare/$', CompareProductsView.as_view(), name='compare'),

    url(r'^add/$', AddProductView.as_view(), name='add'),
    url(r'^add/(?P<pk>\d+)/images/$', AddImagesView.as_view(), name='add-images'),
    url(r'^add/(?P<pk>\d+)/colors/$', AddColorsView.as_view(), name='add-colors'),
    url(r'^add/(?P<pk>\d+)/related/$', AddRelatedProductsView.as_view(), name='add-related'),
    url(r'^add/(?P<pk>\d+)/complete/$', AddCompleteView.as_view(), name='add-complete'),
]

lk/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import (ProfileHomeView, ProfileTemplateView, OrderView, EditProfileView, RemoveProfileView,
                    SellerTemplateView, SellerOrdersView, InvoiceRequestView, DocumentsRequestView,
                    ProductsView, ProductView,
                    ProductEditView, ProductEditImagesView, ProductEditColorsView, ProductEditRelatedView)
from .api_views import AddToFavorites, RemoveFromFavorites, AddToCompare, RemoveFromCompare
from .update_views import HumanUpdateView, FirstCompanyUpdateView, SecondCompanyUpdateView, PasswordUpdateView


urlpatterns = [
    url(r'^$', ProfileHomeView.as_view(), name='home'),
    url(r'^remove/$', RemoveProfileView.as_view(), name='remove'),

    url(r'^orders/$', ProfileTemplateView.as_view(template_name='profile/orders.html'), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', OrderView.as_view(), name='order'),

    # url(r'^reviews/$', ProfileTemplateView.as_view(template_name='profile/reviews.html'), name='reviews'),
    url(r'^reviews/$', RedirectView.as_view(pattern_name='profile:home', permanent=False), name='reviews'),

    url(r'^wishlist/$', ProfileTemplateView.as_view(template_name='profile/wishlist.html'), name='wishlist'),
    url(r'^favorites/add/$', AddToFavorites.as_view(), name='add-to-favorites'),
    url(r'^favorites/remove/$', RemoveFromFavorites.as_view(), name='remove-from-favorites'),

    url(r'^compare/add/$', AddToCompare.as_view(), name='add-to-compare'),
    url(r'^compare/remove/$', RemoveFromCompare.as_view(), name='remove-from-compare'),

    url(r'^seller_orders/$', SellerOrdersView.as_view(), name='seller-orders'),

    url(r'^products/$', ProductsView.as_view(), name='products'),
    url(r'^products/(?P<pk>\d+)/$', ProductView.as_view(), name='product'),
    url(r'^products/(?P<pk>\d+)/edit/$', ProductEditView.as_view(), name='product-edit'),
    url(r'^products/(?P<pk>\d+)/edit/images/$', ProductEditImagesView.as_view(), name='product-edit-images'),
    url(r'^products/(?P<pk>\d+)/edit/colors/$', ProductEditColorsView.as_view(), name='product-edit-colors'),
    url(r'^products/(?P<pk>\d+)/edit/related/$', ProductEditRelatedView.as_view(), name='product-edit-related'),

    url(r'^invoice/$', InvoiceRequestView.as_view(), name='invoice'),
    url(r'^documents/$', DocumentsRequestView.as_view(), name='documents'),

    url(r'^edit/$', EditProfileView.as_view(), name='edit'),
    url(r'^edit/human/$', HumanUpdateView.as_view(), name='update-human'),
    url(r'^edit/company/1/$', FirstCompanyUpdateView.as_view(), name='update-company-1'),
    url(r'^edit/company/2/$', SecondCompanyUpdateView.as_view(), name='update-company-2'),
    url(r'^edit/password/$', PasswordUpdateView.as_view(), name='update-password'),
]

main/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from lk.auth_views import SellerRegistrationView, AjaxLoginView
from catalog.views import ProductRequestView
from content.views import IndexView, PageView, AboutUsPageView, FeedbackFormView, SubscribeFormView, SearchView
from support.views import SupportView, SupportSearchView, QuestionFormView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),
    url(r'^500/$', TemplateView.as_view(template_name='500.html'), name='500'),
    url(r'^about/$', AboutUsPageView.as_view(), name='about'),

    url(r'^support/$', SupportView.as_view(), name='support'),
    url(r'^support/search/$', SupportSearchView.as_view(), name='support-search'),

    # url(r'^auth/',  include('lk.auth.urls', namespace='auth')),
    url(r'^auth/', include('registration.backends.default.urls')),
    url(r'^auth/register/seller/$', SellerRegistrationView.as_view(), name='seller_registration_register'),
    url(r'^auth/login/ajax/$', AjaxLoginView.as_view(), name='auth-ajax-login'),

    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^alazone-adm/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^treenav/', include('treenav.urls')),

    url(r'^profile/',  include('lk.urls', namespace='profile')),
    url(r'^cart/',  include('cart.urls', namespace='cart')),
    url(r'^basket/',  include('cart.api.urls', namespace='basket')),
    url(r'^shop/',  include('catalog.urls', namespace='shop')),
    url(r'^blog/',  include('blog.urls', namespace='blog')),

    # url(r'^forms/', include('feedback.urls', namespace='forms')),
    url(r'^feedback_form/$', FeedbackFormView.as_view(), name='feedback-form'),
    url(r'^subscribe_form/$', SubscribeFormView.as_view(), name='subscribe-form'),
    url(r'^question_form/$', QuestionFormView.as_view(), name='question-form'),
    url(r'^request_form/$', ProductRequestView.as_view(), name='request-form'),

    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^(?P<slug>[^/]+)/$', PageView.as_view(), name='page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.core.urlresolvers import reverse
from django.db import models

from django_pgjson.fields import JsonField
from django_hstore import hstore
from mptt.models import MPTTModel, TreeForeignKey

from lk.models import Profile
from site_settings.models import Setting, SEOSetting
from .utils import slugify


class Category(MPTTModel):
    title = models.CharField('Заголовок', max_length=255)
    slug = models.SlugField('В url', unique=True, max_length=255)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', verbose_name='Родитель')

    cover = models.ImageField('Обложка', null=True, blank=True, upload_to='catalog/categories/')
    order = models.IntegerField('Порядок', default=10)
    description = models.TextField('Краткое описание', blank=True, null=True)

    show = models.BooleanField('Показывать на сайте', default=True)
    use_home4 = models.BooleanField('Использовать шаблон Home4', default=False)

    # Сериализованные поля в фильтре
    attrs = JsonField(null=True, blank=True, editable=False)

    def __unicode__(self):
        return self.title

    class Meta:
        app_label = 'catalog'
        ordering = ['order', 'id', ]
        verbose_name = 'категория'
        verbose_name_plural = 'категории товаров'

    def get_absolute_url(self):
        return reverse('shop:category', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        super(Category, self).save(*args, **kwargs)
        self.update_json_attrs()
        return super(Category, self).save(*args, **kwargs)

    def update_json_attrs(self):
        attrs = []

        for attr in self.attribute_set.all():
            attr_dict = {
                'name': attr.slug,
                'class': attr.attr_type,
                'kwargs': {
                    'verbose_name': attr.title,
                }
            }
            new_attr_dict = {
                'name': attr.slug + '-new',
                'class': attr.attr_type,
                'kwargs': {
                    'verbose_name': attr.title + ' (новое значение)',
                }
            }
            if not attr.required:
                attr_dict['kwargs']['blank'] = True
            new_attr_dict['kwargs']['blank'] = True

            if attr.attr_type == 'CharField':
                attr_dict['kwargs']['max_length'] = 255
                new_attr_dict['kwargs']['max_length'] = 255
            attrs.append(attr_dict)
            attrs.append(new_attr_dict)

        self.attrs = attrs

    meta_title = models.CharField(
        'Meta title (заголовок страницы)',
        max_length=255, blank=True,
        help_text='Оставьте пустым, чтобы использовать поле "Заголовок"',
    )
    meta_description = models.CharField(
        'Meta description (описание страницы)',
        max_length=255, blank=True,
        help_text='Оставьте пустым, чтобы использовать глобальный meta_desc',
    )
    meta_keywords = models.CharField(
        'Meta keywords (ключевые слова через запятую)',
        max_length=255, blank=True,
        help_text='Оставьте пустым, чтобы использовать глобальный meta_keyw',
    )

    def get_meta_title(self):
        return self.meta_title if self.meta_title else '{0} — Каталог — Alazone'.format(self.title)

    def get_meta_desc(self):
        return self.meta_description if self.meta_description else SEOSetting.objects.get(key='global').meta_desc

    def get_meta_keyw(self):
        return self.meta_keywords if self.meta_keywords else SEOSetting.objects.get(key='global').meta_keyw

    @property
    def shown_children(self):
        return self.children.filter(show=True)

    @property
    def me_with_children(self):
        categories = [self.id]
        categories.extend(self.get_descendants().values_list('id', flat=True))
        return categories

    @property
    def color_set(self):
        colors = set(ProductColor.objects.filter(
            product__category_id__in=self.me_with_children, product__show=True
        ).values_list('hex_value', flat=True))
        return [color.split('#')[-1] for color in colors]

    @property
    def products(self):
        categories = [self.id]
        categories.extend(self.get_descendants().values_list('id', flat=True))
        return Product.objects.filter(category_id__in=self.me_with_children, show=True)

    def get_attrs(self):
        return [field for field in self.attrs if not field['name'].endswith('-new')]

    def get_new_attrs(self):
        return [field for field in self.attrs if field['name'].endswith('-new')]

    def get_attrs_with_values(self):
        products = self.products
        attrs = []
        for attr in self.get_attrs():
            a_name = attr['name']
            attr_dict = {
                'attr': attr,
                'values': ['Да', 'Нет'] if attr['class'] == 'BooleanField' else sorted(list(set(
                    [value for value in products.extra(
                        select={a_name: "catalog_product.attrs -> '{0}'".format(a_name)}
                    ).values_list(a_name, flat=True) if value]
                ))),
            }
            attrs.append(attr_dict)
        return attrs


class Attribute(models.Model):
    TYPE_CHOICES = (
        ('CharField', 'строка'),
        ('IntegerField', 'целое число'),
        ('FloatField', 'число с плавающей запятой'),
        ('DateField', 'дата'),
        ('BooleanField', 'логическая переменная ("да/нет")'),
    )
    category = models.ForeignKey(Category, verbose_name='Категория')
    title = models.CharField('Имя поля', max_length=255)
    slug = models.CharField(max_length=255, editable=False)
    attr_type = models.CharField('Тип поля', max_length=255, choices=TYPE_CHOICES)
    required = models.BooleanField('Обязательное поле?', default=False)
    # multiple_choices = models.BooleanField('Выбор из определенных вариантов', default=False)
    # choices = models.TextField('Варианты', null=True, blank=True,
    #                            help_text='Каждый вариант на новой строке; не забудьте проставить галочку сверху')
    # multiple_filter_choices = models.BooleanField('Фильтрация по нескольким', default=False)
    order = models.IntegerField('Порядок', default=10)

    def __unicode__(self):
        return self.title

    class Meta:
        app_label = 'catalog'
        ordering = ['order', 'id', ]
        unique_together = ('category', 'title',)
        unique_together = ('category', 'slug',)
        verbose_name = 'поле'
        verbose_name_plural = 'поля'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        save = super(Attribute, self).save(*args, **kwargs)
        self.category.update_json_attrs()
        return save


class ProductManager(models.Manager):

    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(removed=False)


class Product(models.Model):
    DELIVERY_CHOICES = (
        ('regions', 'по регионам'),
        ('abroad', 'зарубеж'),
    )
    CONDITION_CHOICES = (
        ('new', 'новый'),
        ('used', 'б/у'),
    )
    category = models.ForeignKey(Category, verbose_name=u'Категория')
    seller = models.ForeignKey(Profile, verbose_name='Продавец', limit_choices_to={'profile_type': 'company'})

    # старые поля (отображаются на сайте)
    title = models.CharField('Название', max_length=255)
    price = models.DecimalField('Цена, тнг', max_digits=18, decimal_places=2, blank=True, null=True)
    new_price = models.DecimalField('Цена после скидки, тнг', max_digits=18, decimal_places=2, blank=True, null=True)
    quantity = models.SmallIntegerField('Количество', default=0)
    delivery_type = models.CharField('Тип доставки', max_length=15, choices=DELIVERY_CHOICES, default='regions')
    condition = models.CharField('Состояние товара', max_length=5, choices=CONDITION_CHOICES, default='new')
    description = models.TextField('Краткое описание', null=True, blank=True)

    # новые поля (не отображаются до подтверждения модератором)
    title_new = models.CharField('Название (новое значение)', max_length=255)
    price_new = models.DecimalField('Цена, тнг (новое значение)',
                                    max_digits=18, decimal_places=2, blank=True, null=True)
    new_price_new = models.DecimalField('Цена после скидки, тнг (новое значение)',
                                        max_digits=18, decimal_places=2, blank=True, null=True)
    quantity_new = models.SmallIntegerField('Количество (новое значение)', default=0)
    delivery_type_new = models.CharField('Тип доставки (новое значение)', max_length=15,
                                         choices=DELIVERY_CHOICES, default='regions')
    condition_new = models.CharField('Состояние товара (новое значение)', max_length=5,
                                     choices=CONDITION_CHOICES, default='new')
    description_new = models.TextField('Краткое описание (новое значение)', null=True, blank=True)

    attrs = hstore.DictionaryField(null=True, blank=True)  # db_index=True?

    show = models.BooleanField('Показывать на сайте', default=False,
                               help_text='Проставьте галку, чтобы опубликовать товар')
    updated = models.BooleanField('Товар был изменен', default=False, help_text='и ждет проверки')
    apply_changes = models.BooleanField('Товар проверен', default=True,
                                        help_text='Проставьте галку, чтобы применить последние изменения')
    removed = models.BooleanField('Удалить товар', default=False, help_text='Проставьте галку, чтобы удалить товар')

    at_homepage_catalog = models.BooleanField('Вынести на главную (в товары по категориям)', default=True)
    at_homepage_slider = models.BooleanField('Вынести на главную (в слайдер о новых/популярных товарах)', default=False)
    at_sidebar = models.BooleanField('Вынести в сайдбар (в продвигаемые товары)', default=False)

templates/catalog/wizard/add_colors.html
{% extends "base.html" %}
{% load staticfiles %}

{% block meta_title %}Добавление цветов для товара &quot;{{ product.title }}&quot; — Alazone{% endblock %}

{% block content %}
	<section id="content">
		<div id="breadcrumb-container">
			<div class="container">
				<ul class="breadcrumb">
					<li><a href="{% url 'index' %}">Главная</a></li>
					<li class="active">Цвета для &quot;{{ product.title }}&quot;</li>
				</ul>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<header class="content-title">
						<h1 class="title">Добавление товара - шаг №3</h1>
                        <p class="title-desc">
                            Поздравляем! Вы успешно добавили новый товар &quot;{{ product.title }}&quot;. Он будет опубликован на сайте после одобрения модератором.<br><br>
                            Теперь Вы можете добавить цвета для Вашего товара.
                        </p>
					</header>
					<div class="xs-margin"></div>
					<form action="{{ request.path }}" method="post">
						{% csrf_token %}
						<div class="row">
							<div class="col-md-6 col-sm-6 col-xs-12">
								<fieldset style="margin-bottom: 30px;">
									<div class="colors-box">
										<div id="color-item-template" class="color-item">
											<div class="input-group">
												<span class="input-group-addon"><span class="input-text">Цвет&#42;</span></span>
												<input type="text" name="color[0]" class="form-control input-lg color_select" value="#ffffff" required>
											</div>
											<div class="input-group">
												<span class="input-group-addon"><span class="input-text">Название&#42;</span></span>
												<input type="text" name="color_name[0]" required class="color_name form-control input-lg" placeholder="Название цвета товара">
											</div>
											<div class="input-group color_remove_button" style="display: none;">
												<button type="button" class="add-product-remove-color" class="btn btn-default">Удалить цвет</button>
											</div>
										</div>
									</div>
								</fieldset>
								<div class="input-group">
									<button type="button" id="add-product-add-color" style="margin-top: -40px;" class="btn btn-default">Добавить еще один цвет</button>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 col-sm-6 col-xs-12">
								<input type="submit" value="СОХРАНИТЬ" class="btn btn-custom-2 md-margin">
								{% if request.user.product_set.count > 1 %}
                                	<a href="{% url 'shop:add-related' product.id %}" class="btn btn-link md-margin">ПРОПУСТИТЬ >></a>
                                {% else %}
                                	<a href="{% url 'shop:add-complete' product.id %}" class="btn btn-link md-margin">ПРОПУСТИТЬ >></a>
                                {% endif %}
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

{% block extra_js %}
	<script src="{% static 'js/minicolor/jquery.minicolors.min.js' %}"></script>
	<script>
		$('.color_select', $('#color-item-template')).minicolors({theme: 'bootstrap'});
		var colors_counter = 1;

		$('#add-product-add-color').on('click', function(){
			var color_item = $('#color-item-template').clone();
			color_item.attr('id', '');

			var color_input = $('.color_select', color_item);
			color_input.minicolors('destroy');
			color_input.val('#ffffff');
			color_input.attr('name', 'color['+colors_counter+']');
			color_input.minicolors({theme: 'bootstrap'});

			var color_name = $('.color_name', color_item);
			color_name.attr('name', 'color_name['+colors_counter+']');
			color_name.val('');

			var color_remove_button = $('.color_remove_button', color_item);
			color_remove_button.show();

			var color_box = $('.colors-box');
			color_box.append(color_item);
			color_item.show();

			colors_counter++;
		});

		$('.colors-box').on('click', '.add-product-remove-color', function(){
			var color_item = $(this).parent().parent();
			color_item.remove();
			colors_counter--;

			$('.colors-box').find('.color-item').each(function(i) {
				var item = $(this);
				$('.color_select', item).attr('name', 'color[' + i + ']');
				$('.color_name', item).attr('name', 'color_name[' + i + ']');
			});
		});
	</script>
{% endblock %}

templates/catalog/wizard/add_product.html
{% extends "base.html" %}

{% block meta_title %}Добавление товара — Alazone{% endblock %}

{% block content %}
	<section id="content">
		<div id="breadcrumb-container">
			<div class="container">
				<ul class="breadcrumb">
					<li><a href="{% url 'index' %}">Главная</a></li>
					<li class="active">Добавление товара</li>
				</ul>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<header class="content-title">
						<h1 class="title">Добавление товара - шаг №1</h1>
						<p class="title-desc">Добавление товара, который вы собираетесь продать.</p>
					</header>
					<div class="xs-margin"></div>
					<form action="{{ request.path }}" method="post">
						{% csrf_token %}
						<div class="row">
							<div class="col-md-6 col-sm-6 col-xs-12">
								<fieldset>
									<div class="help-block input-error">{{ form.non_field_errors }}</div>
									<div class="help-block input-error">{{ form.category.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">Категория&#42;</span></span>
										{{ form.category }}
									</div>
									<div class="help-block input-error">{{ form.title.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">Название&#42;</span></span>
										<input type="text" name="title" value="{{ form.title.value|default:'' }}" required class="form-control input-lg" placeholder="Название товара">
									</div>
									<div class="help-block input-error">{{ form.article.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">Код&#42;</span></span>
										<input type="text" name="article" value="{{ form.article.value|default:'' }}" required class="form-control input-lg" placeholder="Код товара">
									</div>
									<div class="help-block input-error">{{ form.quantity.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">Количество&#42;</span></span>
										<input type="number" name="quantity" value="{{ form.quantity.value|default:'' }}" required class="form-control input-lg" placeholder="Количество единиц товара">
									</div>
									<div class="help-block input-error">{{ form.price.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">Цена&#42;</span></span>
										<input type="text" name="price" value="{{ form.price.value|default:'' }}" required class="form-control input-lg" placeholder="Цена товара">
									</div>
									<div class="help-block input-error">{{ form.new_price.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">Скидочная цена</span></span>
										<input type="text" name="new_price" value="{{ form.new_price.value|default:'' }}" class="form-control input-lg" placeholder="Скидочная цена">
									</div>
									<div class="help-block input-error">{{ form.delivery_type.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">Тип доставки&#42;</span></span>
										{{ form.delivery_type }}
									</div>
									<div class="help-block input-error">{{ form.condition.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">Состояние товара&#42;</span></span>
										{{ form.condition }}
									</div>
									<div id="attr_fields">
									  {% if form.category.value %}
										{% include 'catalog/include/category_fields.html' with category_id=form.category.value %}
									  {% endif %}
									</div>
								</fieldset>
							</div>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<fieldset>
									<div class="help-block input-error">{{ form.description.errors }}</div>
									<div class="input-group">
										<!--<span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">Описание&#42;</span></span>-->
										<p><span class="input-text" style="color: #ef4043">Описание&#42;</span></p>
										<textarea name="description" required class="form-control input-lg" style="height: 262px;">{{form.description.value|default:''}}</textarea>
									</div>
								</fieldset>
							</div>
							<!--<div class="col-md-12 col-sm-12 col-xs-12">
								<fieldset>
									<div class="help-block input-error">{{ form.meta_title.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">SEO заголовок<br>страницы</span></span>
										<input type="text" name="meta_title" value="{{ form.meta_title.value|default:'' }}" class="form-control input-lg" placeholder="Meta title (заголовок страницы)">
									</div>
									<div class="help-block input-error">{{ form.meta_description.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">SEO описание<br>страницы</span></span>
										<input type="text" name="meta_description" value="{{ form.meta_description.value|default:'' }}" class="form-control input-lg" placeholder="Meta title (заголовок страницы)">
									</div>
									<div class="help-block input-error">{{ form.meta_keywords.errors }}</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-text">SEO ключевые<br> слова <small>(через запятую)</small></span></span>
										<input type="text" name="meta_keywords" value="{{ form.meta_keywords.value|default:'' }}" class="form-control input-lg" placeholder="Meta title (заголовок страницы)">
									</div>
								</fieldset>
							</div>-->
						</div>
						<div class="row">
							<div class="col-md-6 col-sm-6 col-xs-12">
								<input type="submit" value="ДАЛЕЕ >>" class="btn btn-custom-2 md-margin">
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

{% block extra_js %}
	<script>
		$('#id_category').change(function() {
			var category_id = $(this).val(),
				base_url = "{% url 'shop:get-category-attrs' 0 %}",
				url = base_url.replace('/0/', '/' + category_id + '/');
			$.get(url, {}, function(res) {
				$('#attr_fields').html(res);
			});
		});
	</script>
{% endblock %}

templates/catalog/wizard/complete.html
{% extends "base.html" %}

{% block meta_title %}Добавление товара — Alazone{% endblock %}

{% block content %}
    <section id="content">
        <div id="breadcrumb-container">
            <div class="container">
                <ul class="breadcrumb">
                    <li><a href="{% url 'index' %}">Главная</a></li>
                    <li class="active">Добавление товара &quot;{{ product.title }}&quot;</li>
                </ul>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <header class="content-title">
                        <h1 class="title">Поздравляем!</h1>
                        <p class="title-desc">Вы успешно добавили новый товар &quot;{{ product.title }}&quot;.<br><br>Он будет опубликован на сайте после одобрения модератором.</p>
                    </header>
                    <div class="xs-margin"></div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}